name: Compress Images on Push to master branch
on:
  push:
    branches:
      - master
    paths:
      - 'public/images/uploads/**.jpg'
      - 'public/images/uploads/**.jpeg'
      - 'public/images/uploads/**.png'
      - 'public/images/uploads/**.webp'
      - 'public/images/uploads/**.avif'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          compressOnly: true
          minPctChange: '20'
      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v4
        with:
          title: Compressed Images
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}